apiVersion: v1
kind: Service
metadata:
  name: {{ include "three-tier-app.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "three-tier-app.labels" . | nindent 4 }}

spec:
  selector:
    app: backend

  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}

  type: ClusterIP