apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "three-tier-app.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "three-tier-app.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.frontend.replicaCount }}

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend

          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"

          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}

          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10